// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFNLNeLrKG60KOU-b0u9VdrQYFfvLlG-w',
    appId: '1:737972843609:web:879f619db4bf346bf82d48',
    messagingSenderId: '737972843609',
    projectId: 'video-chat-702fc',
    authDomain: 'video-chat-702fc.firebaseapp.com',
    storageBucket: 'video-chat-702fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ0yeMzBlHHXbHOwjdOwCGwUG-NrGfpOE',
    appId: '1:737972843609:android:d386ab94321d1484f82d48',
    messagingSenderId: '737972843609',
    projectId: 'video-chat-702fc',
    storageBucket: 'video-chat-702fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmRF9MkP95jeeP0agf-radPDJ-B77qj4g',
    appId: '1:737972843609:ios:47c76b0ef26b8455f82d48',
    messagingSenderId: '737972843609',
    projectId: 'video-chat-702fc',
    storageBucket: 'video-chat-702fc.appspot.com',
    androidClientId: '737972843609-f28ob5jiga8c8pbkdlt7i5asup9ien29.apps.googleusercontent.com',
    iosClientId: '737972843609-84qbv8h7g94v3jkd2ccgdp6k1p8bk0rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmRF9MkP95jeeP0agf-radPDJ-B77qj4g',
    appId: '1:737972843609:ios:dfe50ffb696a70a8f82d48',
    messagingSenderId: '737972843609',
    projectId: 'video-chat-702fc',
    storageBucket: 'video-chat-702fc.appspot.com',
    androidClientId: '737972843609-f28ob5jiga8c8pbkdlt7i5asup9ien29.apps.googleusercontent.com',
    iosClientId: '737972843609-hd13a3b779pt2oap1enhtqheaq94jurn.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoChat.RunnerTests',
  );
}
